org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.0
forge_version_range=[47,)
loader_version_range=[47,)
jei_version=15.2.0.27
jade_id=4986594
endless_id=6878622
iaf_id=5633453
citadel_id=6702068
de_id=6793843
curios_id=6418456
ccl_id=5753868
bc_id=5422013
bot_ver=448-FORGE
patchouli_ver=84.1-FORGE
tf_id=5468648

mapping_channel=official
mapping_version=1.20.1
mod_id=orecrop
mod_name=Ore Crop
mod_license=MIT
mod_version=1.20.1-0.3.1
mod_group_id=com.yuo
mod_authors=yuo
mod_description=Ore Crop