modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
[[mods]] #mandatory
modId="orecrop"
version="1.16.5-1.2.9"
displayName="OreCrop"
authors="yuo" 
description='''
矿石作物。1.16.5
'''
